[[news]]
date = "2026-5"
content = "One first-author paper has been accepted by **KDD 2026** (CCF-A)."

[[news]]
date = "2025-7"
content = "One co-first-author paper has been accepted by **ECAI 2025** (CCF-B)."

[[news]]
date = "2025-5"
content = "One first-author paper has been accepted by **ICML 2025** (CCF-A)."

[[news]]
date = "2024-10"
content = "One first-author paper has been accepted by **NeurIPS 2024** (CCF-A)."
